language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
env:
  - REDIS_ADDR="localhost:6379" APPENGINE_DEV_APPSERVER="$HOME/google-cloud-sdk/bin/dev_appserver.py"
services:
  - redis-server
before_install:
  - curl https://sdk.cloud.google.com > install.sh && chmod +x install.sh
install:
  - "./install.sh --disable-prompts"
  - "$HOME/google-cloud-sdk/bin/gcloud components install beta --quiet"
  - "$HOME/google-cloud-sdk/bin/gcloud components install cloud-datastore-emulator --quiet"
  - "$HOME/google-cloud-sdk/bin/gcloud components install app-engine-python --quiet"
  - "$HOME/google-cloud-sdk/bin/gcloud components install app-engine-go --quiet"
  - go get -v -d -t ./...
before_script:
  - "$HOME/google-cloud-sdk/bin/gcloud config set project nds-test"
  - "$HOME/google-cloud-sdk/bin/gcloud beta emulators datastore start --quiet &"
  - sleep 15
  - "$($HOME/google-cloud-sdk/bin/gcloud beta emulators datastore env-init)"
script:
  - go test -covermode=count -coverprofile=profile.cov -coverpkg=$(go list ./... | grep -v '/vendor/' | paste -sd, -) ./...
after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci
