language: go
sudo: false
go:
  - 1.10.x
env:
  - CLOUDSDK_CORE_PROJECT="NDSTEST" REDIS_ADDR="localhost:6379"
services:
  - redis-server
before_install:
  - wget -O go_appengine_sdk_linux_amd64.zip https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.68.zip
  - unzip -q -d $HOME go_appengine_sdk_linux_amd64.zip
  - export PATH=$PATH:$HOME/go_appengine
  - curl https://sdk.cloud.google.com > install.sh && chmod +x install.sh
install:
  - "./install.sh --disable-prompts"
  - "$HOME/google-cloud-sdk/bin/gcloud components install beta --quiet"
  - "$HOME/google-cloud-sdk/bin/gcloud components install cloud-datastore-emulator --quiet"
  - goapp get -v -d -t ./...
before_script:
  - "$HOME/google-cloud-sdk/bin/gcloud beta emulators datastore start --quiet &"
  - sleep 15
  - "$($HOME/google-cloud-sdk/bin/gcloud beta emulators datastore env-init)"
script:
  - go test -v -covermode=count -coverprofile=profile.cov -coverpkg=$(shell go list ./... | grep -v '/vendor/' | paste -sd, -) ./...
  - goapp test -v -covermode=count -coverprofile=aeprofile.cov -coverpkg=$(shell go list ./... | grep -v '/vendor/' | paste -sd, -) ./
after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - cat aeprofile.cov | grep .go >> profile.cov
  - goveralls -coverprofile=profile.cov -service=travis-ci
